### ISSUE TITLE
I am not able to build it for android

### ISSUE THREAD

**Issue by snj07** [Abhilash-Chandran/flutter_web_htmlelementview_test#2]

**Comment by Abhilash-Chandran** [comment]
@snj07  Could you specify what issue are you facing exactly.?

**Comment by snj07** [comment]
It's working for web app but when we build it for android app then it does not work.

**Comment by Abhilash-Chandran** [comment]
@snj07 The purpose of this app was to explain the issues with flutter web. This code will not build for any other platform especially because it uses plotly's javascript library and also `HtmlLElementView` widget which is from `dart:html` library which is only available for web platform.
